name: agile_families_toon
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  html: ^0.15.0
  http: ^0.13.0
  shelf_static: ^1.1.2
  path: ^1.9.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
